---
# tasks file for frontends
- name: "install frontend packages: {{ haproxy_packages }}"
  yum:
    name: "{{item}}"
    state: latest
  with_items: "{{ haproxy_packages }}"

- name: enable and start haproxy
  service:
    name: haproxy
    enabled: True
    state: started

- name: add haproxy configuration file
  block:
   - template:
       src: haproxy.cfg.j2
       dest: /etc/haproxy/haproxy.cfg
     notify: reload haproxy
  rescue:
    - debug:
        msg: could not update haproxy
        verbosity: 2
  always:
    - debug:
        msg: sending notification, attempted update to haproxy cfg
        verbosity: 2
