---
# tasks file for frontends
- name: "install frontend packages: {{ haproxy_packages }}"
  yum:
    name={{item}} state=latest
  with_items: "{{ haproxy_packages }}''"

- name: enable and start haproxy
  service: name=haproxy enabled=True state=started

- name: Add HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: reload haproxy
