- name: setup frontends
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  vars:
    GUID:  "{{ lookup('env','GUID') }}"
  roles:
    - role: frontends
  tags:
    - setup frontends
