---
# tasks file for appdbs
- name: install progress
  yum: name=postgresql-server state=latest
  notify: start and enable postgres

- name: Init postgres
  command: "postgresql-setup initdb"
  run_once: True
  #with_items:
    #- "chkconfig postgresql on"
