---
# tasks file for appdbs
- name: install progres
  yum: name=postgresql-server state=latest
  notify:
    - start postgres
    - enable postgres

- name: Init postgres
  command: "postgresql-setup initdb"
  run_once: True
  #with_items:
    #- "chkconfig postgresql on"
